numeros = []
print("11) Peça ao usuário para inserir três números. Determine o maior e o menor entre eles.\n\n")
numero = int(input("Digite o primeiro número:\n"))
numeros.append(numero)
numero = int(input("Digite o segundo número:\n"))
numeros.append(numero)
numero = int(input("Digite o terceiro número:\n"))
numeros.append(numero)
numeros.sort(reverse=True)
print("Maiores: ", numeros)